services:
  mongodb:
    image: mongo:latest
    container_name: momentum-mongodb
    ports:
      - "27017:27017"
    volumes:
      - momentum_mongodb_data:/data/db
    networks:
      - "db_network"
  
  backend:
    image: momentum-backend:latest
    container_name: momentum-backend
    ports:
      - "8080:8080"
    networks:
      - "db_network"
    environment:
      NODE_ENV: "production"
      MONGODB_URI: "mongodb://momentum-mongodb:27017/momentum"

networks:
  db_network:

volumes:
  momentum_mongodb_data:
